import { PodcastDialogue } from '../types';
import { CURATED_VOICES } from './voices';

const voiceFrancisca = CURATED_VOICES.find((v) => v.id === 'pt-BR-FranciscaNeural') || CURATED_VOICES[0];
const voiceAntonio = CURATED_VOICES.find((v) => v.id === 'pt-BR-AntonioNeural') || CURATED_VOICES[2];
const voiceBruno = CURATED_VOICES.find((v) => v.id === 'en-US-BrianMultilingualNeural') || CURATED_VOICES[4];
const voiceThalita = CURATED_VOICES.find((v) => v.id === 'pt-BR-ThalitaMultilingualNeural') || CURATED_VOICES[1];
const voiceAndre = CURATED_VOICES.find((v) => v.id === 'en-US-AndrewMultilingualNeural') || CURATED_VOICES[3];

export const SAMPLE_DIALOGUES: PodcastDialogue[] = [
  {
    id: 'podcast-tech-1',
    title: 'Vozes do Futuro: Inteligência Artificial e Podcasts',
    description: 'Um bate-papo dinâmico entre Carlos e Mariana discutindo a evolução da fala sintética e suas aplicações práticas para criadores de conteúdo.',
    category: 'Tecnologia & Inovação',
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
    updatedAt: Date.now() - 1000 * 60 * 60 * 20,
    characters: [
      {
        id: 'char-carlos',
        name: 'Carlos',
        voice: voiceAntonio,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'cyan',
        role: 'Host do Podcast',
      },
      {
        id: 'char-mariana',
        name: 'Mariana',
        voice: voiceFrancisca,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'rose',
        role: 'Especialista Convidada',
      },
    ],
    lines: [
      {
        id: 'line-1',
        characterId: 'char-carlos',
        text: 'Fala pessoal! Sejam todos muito bem-vindos a mais um episódio do Vozes do Futuro. Hoje estou com a Mariana pra debater algo que parecia ficção científica até pouco tempo atrás.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 0,
      },
      {
        id: 'line-2',
        characterId: 'char-mariana',
        text: 'Oi Carlos, e olá a todos que estão nos ouvindo! É um prazer enorme estar aqui. O assunto de hoje realmente está transformando a forma como consumimos áudio.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 1,
      },
      {
        id: 'line-3',
        characterId: 'char-carlos',
        text: 'Mariana, o que mais me impressiona é a entonação natural. As vozes neurais de hoje respeitam respirações, pontuações e até hesitações sutis que dão calor humano à conversa.',
        pauseAfterSeconds: 0.5,
        status: 'pending',
        order: 2,
      },
      {
        id: 'line-4',
        characterId: 'char-mariana',
        text: 'Com certeza! Isso derruba uma barreira gigantesca para criadores de conteúdo, educadores e desenvolvedores. Antes, montar um podcast com múltiplos participantes exigia microfones caros e estúdio isolado.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 3,
      },
      {
        id: 'line-5',
        characterId: 'char-carlos',
        text: 'Exatamente. Agora qualquer pessoa com uma boa ideia e um roteiro bem escrito pode produzir conversas ricas e fluidas com vozes masculinas e femininas perfeitamente calibradas.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 4,
      },
      {
        id: 'line-6',
        characterId: 'char-mariana',
        text: 'E o resultado final soa tão envolvente que prende o ouvinte do primeiro ao último segundo. Vamos ao próximo tópico da nossa pauta?',
        pauseAfterSeconds: 0.3,
        status: 'pending',
        order: 5,
      },
    ],
  },
  {
    id: 'podcast-misterio-2',
    title: 'Café com Mistério: Relatos do Inexplicável',
    description: 'Lucas e Beatriz conversam sobre casos reais e lendas urbanas que desafiam a lógica moderna.',
    category: 'Mistério & Suspense',
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
    updatedAt: Date.now() - 1000 * 60 * 60 * 10,
    characters: [
      {
        id: 'char-lucas',
        name: 'Lucas',
        voice: voiceBruno,
        settings: { rate: '+0%', pitch: '-15Hz', volume: '+0%' },
        avatarColor: 'violet',
        role: 'Investigador',
      },
      {
        id: 'char-beatriz',
        name: 'Beatriz',
        voice: voiceThalita,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'emerald',
        role: 'Apresentadora',
      },
    ],
    lines: [
      {
        id: 'line-m1',
        characterId: 'char-beatriz',
        text: 'Boa noite a todos. Puxem uma cadeira e sirvam uma xícara de café, porque a história de hoje aconteceu em um vilarejo isolado no outono de noventa e quatro.',
        pauseAfterSeconds: 0.5,
        status: 'pending',
        order: 0,
      },
      {
        id: 'line-m2',
        characterId: 'char-lucas',
        text: 'Beatriz, quando eu tive acesso aos registros da delegacia local, confesso que até eu fiquei surpreso. Vários moradores relataram as mesmas luzes azuis nos topos das montanhas.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 1,
      },
      {
        id: 'line-m3',
        characterId: 'char-beatriz',
        text: 'E o mais curioso é que nenhum barulho foi registrado pelos sensores acústicos da região florestal.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 2,
      },
      {
        id: 'line-m4',
        characterId: 'char-lucas',
        text: 'Exato. Um silêncio absoluto, como se todo o ambiente ao redor tivesse sido pausado no tempo.',
        pauseAfterSeconds: 0.3,
        status: 'pending',
        order: 3,
      },
    ],
  },
  {
    id: 'podcast-debate-3',
    title: 'Mesa Redonda: Três Criadores e o Mercado Criativo',
    description: 'Debate dinâmico entre três vozes: o apresentador e dois convidados discutindo o futuro do áudio digital.',
    category: 'Negócios & Mídia',
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
    characters: [
      {
        id: 'char-host-andre',
        name: 'André',
        voice: voiceAndre,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'amber',
        role: 'Moderador',
      },
      {
        id: 'char-mariana-deb',
        name: 'Mariana',
        voice: voiceFrancisca,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'rose',
        role: 'Produtora de Conteúdo',
      },
      {
        id: 'char-bruno-deb',
        name: 'Bruno',
        voice: voiceBruno,
        settings: { rate: '+0%', pitch: '+0Hz', volume: '+0%' },
        avatarColor: 'cyan',
        role: 'Diretor de Áudio',
      },
    ],
    lines: [
      {
        id: 'line-d1',
        characterId: 'char-host-andre',
        text: 'Bem-vindos à nossa Mesa Redonda! Mariana e Bruno, é excelente ter vocês dois reunidos hoje para discutir a nova era dos podcasts.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 0,
      },
      {
        id: 'line-d2',
        characterId: 'char-mariana-deb',
        text: 'Obrigada, André! Eu vejo que a agilidade na criação agora permite testar roteiros inteiros antes mesmo de ligar as câmeras.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 1,
      },
      {
        id: 'line-d3',
        characterId: 'char-bruno-deb',
        text: 'Concordo plenamente com a Mariana. Para nós na pós-produção, poder intercalar vozes masculinas e femininas com tempos de resposta perfeitos poupa horas de corte manual.',
        pauseAfterSeconds: 0.4,
        status: 'pending',
        order: 2,
      },
      {
        id: 'line-d4',
        characterId: 'char-host-andre',
        text: 'Sensacional. Vamos aprofundar cada um desses pontos!',
        pauseAfterSeconds: 0.3,
        status: 'pending',
        order: 3,
      },
    ],
  },
];
